# Generated by Django 4.0.10 on 2024-04-17 20:56

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='account_number',
            field=models.UUIDField(default=uuid.UUID('e93fe3dc-4c76-466f-81f4-6ac6024e07c3')),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
