# Generated by Django 4.0.10 on 2024-04-18 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_alter_user_account_number'),
        ('deposit', '0002_deposit_account_number_alter_deposit_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='account_number',
            field=models.UUIDField(default=uuid.UUID('c7c3226a-0d7a-4186-9069-c466621ff786')),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit', to='signup.user'),
        ),
    ]
