# Generated by Django 4.0.10 on 2024-04-18 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0003_alter_deposit_account_number_alter_deposit_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='account_number',
            field=models.UUIDField(default=uuid.UUID('0e4776d9-01b7-4a9a-985f-e78c361282ca')),
        ),
    ]
