# Generated by Django 4.0.10 on 2024-04-18 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0004_alter_deposit_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='account_number',
            field=models.UUIDField(default=uuid.UUID('dd2902d3-a7cd-486d-b110-fc8882530cff')),
        ),
    ]
