# Generated by Django 4.0.1 on 2024-05-01 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sender',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver',
        ),
    ]
