version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - PYTHONUNBUFFERED=1

  mongo:
    image: mongo
    ports:
      - "27017:27017"
