import Head from 'next/head';
import Header from '../components/Header';
import TopCards from '../components/TopCards';
import BarChart from '../components/BarChart';
import TransactionHistory from '../components/TransactionHistory';
import useAuthCheck from '../pages/useAuthCheck'; 

export default function Home() {
  useAuthCheck(); 

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className='bg-gray-100 min-h-screen'>
        <Header />
        <TopCards />
        <div className='p-4 grid md:grid-cols-3 grid-cols-1 gap-4'>
          <BarChart />
          <TransactionHistory />
        </div>
        <div className="container mx-auto p-4">
          <div className="grid grid-cols-2 gap-4">
          </div>
        </div>
      </main>
    </>
  );
}
