# Generated by Django 4.0.10 on 2024-04-17 20:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, default=uuid.UUID('1def08a7-8d61-40cc-a126-f3ee70f73f7e'), max_length=15, unique=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='customappuser_groups', to='auth.group'),
        ),
    ]
