# Generated by Django 4.0.10 on 2024-04-18 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0002_remove_user_phone_number_user_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, default=uuid.UUID('e74b5608-599c-4026-ba69-12d7039fe6bc'), max_length=15, unique=True, verbose_name='Account Number'),
        ),
    ]
