# Generated by Django 4.0.10 on 2024-04-18 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_alter_user_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, default=uuid.UUID('637b8f8f-d9d5-49fb-a5e8-1006d9f23be2'), max_length=15, unique=True, verbose_name='Account Number'),
        ),
    ]
