# Generated by Django 4.0.10 on 2024-04-18 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_alter_user_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_number',
            field=models.CharField(blank=True, default=uuid.UUID('328b952c-5e3c-43a9-806f-0070ccd07c62'), max_length=15, unique=True, verbose_name='Account Number'),
        ),
    ]
