# Generated by Django 4.0.1 on 2024-04-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0004_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
