# Generated by Django 4.0.1 on 2024-04-30 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_user_is_verified_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must start with a digit other than 0 and have a length of 10 digits.', regex='^[1-9]\\d{9}$')], verbose_name='Phone Number'),
        ),
    ]
