# Generated by Django 4.0.1 on 2024-04-30 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0007_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
    ]
