# Generated by Django 4.0.1 on 2024-05-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transfer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='sender',
            new_name='user',
        ),
    ]
