# Generated by Django 4.0.10 on 2024-04-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_alter_user_account_number'),
        ('transfer', '0002_alter_transfer_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transfer', to='signup.user'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfer', to='signup.user'),
        ),
    ]
