# Generated by Django 4.0.10 on 2024-04-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otp', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.CharField(default='3034', max_length=6),
        ),
    ]
