# Generated by Django 4.0.10 on 2024-04-17 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('withdraw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='account_number',
            field=models.CharField(default=uuid.UUID('d6a13f30-e164-4f2b-b9af-546760ca618b'), max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to=settings.AUTH_USER_MODEL),
        ),
    ]
