# Generated by Django 4.0.10 on 2024-04-18 11:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0003_alter_user_account_number'),
        ('withdraw', '0002_withdraw_account_number_alter_withdraw_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='account_number',
            field=models.CharField(default=uuid.UUID('7668eee1-c3f2-4d5e-8757-081fa8aea2b0'), max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraws', to='signup.user'),
        ),
    ]
