# Generated by Django 4.0.10 on 2024-04-18 11:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0003_alter_withdraw_account_number_alter_withdraw_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='account_number',
            field=models.CharField(default=uuid.UUID('9e123e23-439a-425c-85f9-c496be002173'), max_length=15, unique=True),
        ),
    ]
