# Generated by Django 4.0.10 on 2024-04-18 11:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('withdraw', '0004_alter_withdraw_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdraw',
            name='account_number',
            field=models.CharField(default=uuid.UUID('6c14b5ba-d4f9-46dc-b3de-5dd19fd0bd0f'), max_length=15, unique=True),
        ),
    ]
